version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '6000:8000'
      - '6001:8001'
      - '6020:8020'
      - '6030:8030'
      - '6040:8040'
    depends_on:
      - postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let_me_in_match_main_graph
      postgres_db: graph-node
      ipfs: '172.27.0.1:5001'
      ethereum: 'matchMain:https://rpc-2.matchscan.io/'
      GRAPH_LOG: info
  postgres:
    image: postgres:14
    ports:
      - '6432:5432'
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements",
        "-cmax_connections=200"
      ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let_me_in_match_main_graph
      POSTGRES_DB: graph-node
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data